// Mocks generated by Mockito 5.4.6 from annotations
// in noor/test/services/gemma_chat_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:noor/models/gemma_config.dart' as _i3;
import 'package:noor/models/gemma_status.dart' as _i2;
import 'package:noor/services/flutter_gemma_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeModelInfo_0 extends _i1.SmartFake implements _i2.ModelInfo {
  _FakeModelInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGemmaModelConfig_1 extends _i1.SmartFake
    implements _i3.GemmaModelConfig {
  _FakeGemmaModelConfig_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FlutterGemmaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterGemmaService extends _i1.Mock
    implements _i4.FlutterGemmaService {
  MockFlutterGemmaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isInitializing =>
      (super.noSuchMethod(
            Invocation.getter(#isInitializing),
            returnValue: false,
          )
          as bool);

  @override
  _i2.ModelInfo get currentStatus =>
      (super.noSuchMethod(
            Invocation.getter(#currentStatus),
            returnValue: _FakeModelInfo_0(
              this,
              Invocation.getter(#currentStatus),
            ),
          )
          as _i2.ModelInfo);

  @override
  _i5.Stream<_i2.ModelInfo> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i5.Stream<_i2.ModelInfo>.empty(),
          )
          as _i5.Stream<_i2.ModelInfo>);

  @override
  _i3.GemmaModelConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeGemmaModelConfig_1(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i3.GemmaModelConfig);

  @override
  _i5.Future<bool> initialize([_i3.GemmaModelConfig? config]) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [config]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isModelReady() =>
      (super.noSuchMethod(
            Invocation.method(#isModelReady, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Stream<double> downloadModel() =>
      (super.noSuchMethod(
            Invocation.method(#downloadModel, []),
            returnValue: _i5.Stream<double>.empty(),
          )
          as _i5.Stream<double>);

  @override
  _i5.Future<void> deleteModel() =>
      (super.noSuchMethod(
            Invocation.method(#deleteModel, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<dynamic> createChat({
    double? temperature = 0.8,
    int? randomSeed = 1,
    int? topK = 1,
    bool? supportImage = false,
    List<dynamic>? tools,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChat, [], {
              #temperature: temperature,
              #randomSeed: randomSeed,
              #topK: topK,
              #supportImage: supportImage,
              #tools: tools,
            }),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> createSession({
    double? temperature = 0.8,
    int? randomSeed = 1,
    int? topK = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [], {
              #temperature: temperature,
              #randomSeed: randomSeed,
              #topK: topK,
            }),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<void> updateConfig(_i3.GemmaModelConfig? newConfig) =>
      (super.noSuchMethod(
            Invocation.method(#updateConfig, [newConfig]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getMemoryInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getMemoryInfo, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> isGpuAccelerationAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isGpuAccelerationAvailable, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> optimizeResources() =>
      (super.noSuchMethod(
            Invocation.method(#optimizeResources, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
