// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrPH0AvYOF2VkVoMs7aNt9SPVWNExXcOo',
    appId: '1:366236677185:web:5583405ca1019df11342c0',
    messagingSenderId: '366236677185',
    projectId: 'medipal-6dbde',
    authDomain: 'medipal-6dbde.firebaseapp.com',
    storageBucket: 'medipal-6dbde.firebasestorage.app',
    measurementId: 'G-B7SKPKHMW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNXUBX0J5ZibG9qC9aTFYGP3SjIAQfzW4',
    appId: '1:366236677185:android:b0856ed946710d661342c0',
    messagingSenderId: '366236677185',
    projectId: 'medipal-6dbde',
    storageBucket: 'medipal-6dbde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxMbKccpEFpKagUGNjZXlQ6NdToy2kKc0',
    appId: '1:366236677185:ios:af6ccb52069dfdd81342c0',
    messagingSenderId: '366236677185',
    projectId: 'medipal-6dbde',
    storageBucket: 'medipal-6dbde.firebasestorage.app',
    iosBundleId: 'com.example.noor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxMbKccpEFpKagUGNjZXlQ6NdToy2kKc0',
    appId: '1:366236677185:ios:af6ccb52069dfdd81342c0',
    messagingSenderId: '366236677185',
    projectId: 'medipal-6dbde',
    storageBucket: 'medipal-6dbde.firebasestorage.app',
    iosBundleId: 'com.example.noor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrPH0AvYOF2VkVoMs7aNt9SPVWNExXcOo',
    appId: '1:366236677185:web:98dc5e6163cc184e1342c0',
    messagingSenderId: '366236677185',
    projectId: 'medipal-6dbde',
    authDomain: 'medipal-6dbde.firebaseapp.com',
    storageBucket: 'medipal-6dbde.firebasestorage.app',
    measurementId: 'G-BJ0SXWS1N0',
  );
}
